### ISSUE TITLE
How to use DBFlow in multiply modules?

### ISSUE THREAD

**Issue by JamesKarl** [Raizlabs/DBFlow#1057]
DBFlow **Version:3.1.1**
Issue Kind (Bug, Question, Feature): Question

**Description**: 
I created an android project as follow:
**Demo**:
 **base**
 **app**

the module **base** acts as a common module shared by other projects. The module **app** depends on module **base**. 
I configured DBFlow and created tables within module **base**, which works well. I tried to create a new database and tables within module **app** and tried to compile and run the demo. It throw an exception 
`Model object: com.jameskarl.androidcode.models.Tags is not registered with a Database. Did you forget an annotation?`

Then I tried to add the following configuration to the build.gradle of module app and compile it. It printed out the following exception:
`duplicate entry: com/raizlabs/android/dbflow/config/GeneratedDatabaseHolder.class`

`def dbflow_version = "3.1.1"
    //DBFlow
    kapt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
    //compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:${dbflow_version}"`

**### Question**:
I want to initialize DBFlow within the shared module **base** and then create databases and tables within both module **base** and **app**. What should I do?

**Comment by trevjonez** [comment]
The behavior you are after is not possible as far as I know. Currently the models must be aware of their containing database. This means that the database class must be in the library. This will result in the database class being generated at the compile time of the library module. While you would then be able to declare more tables in the application module they ultimately will cause errors due to the library database compilation already having been completed.

**Comment by agrosner** [comment]
hes correct. Not supported as of now.

**Comment by JamesKarl** [comment]
Thanks very much for your reply and efforts.
