### ISSUE TITLE
关于动态创建数据库和表的问题（On the dynamic creation of the database and the table）

### ISSUE THREAD

**Issue by niuyunwang** [Raizlabs/DBFlow#1092]
我想动态的创建数据库和表，根据不同用户登录创建对应的数据库名称和表名称。不知道应该怎么操作
I would like to create a dynamic database and table, according to different user login to create the corresponding database name and table name.Do not know how to operate

**Comment by trevjonez** [comment]
This is not supported based on the current feature set. You can probably achieve this by manually manipulating the database files via `File.renameTo(...)` before initializing dbflow. Dynamic tables are not possible due to hard coded values in the generated code.

基于当前功能集，不支持此选项。 你可以通过在初始化dbflow之前通过`File.renameTo（...）`手动操作数据库文件来实现这一点。 由于生成的代码中有硬编码值，因此无法使用动态表。

**Comment by niuyunwang** [comment]
（File.renameTo） This approach is not reliable，（DBFlow ）After a similar plan to improve what set of functions

**Comment by agrosner** [comment]
Dynamic tables are not supported.
