### ISSUE TITLE
ContentProviderGeneration usage doc is outdated?

### ISSUE THREAD

**Issue by bytehala** [Raizlabs/DBFlow#1134]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
It looks like the documentation for [ContentProvider Generation ](https://github.com/Raizlabs/DBFlow/blob/ad83cbacc0d945d5bae93bb05127804f83d22ab8/usage2/ContentProviderGeneration.md) is outdated.

It seems to now use the form `@TableEndpoint(name = ContentProviderModel.NAME, contentProvider = ContentDatabase.class)`

I'm not sure though.

**Comment by Chezlui** [comment]
Same doubts, @agrosner

**Comment by trevjonez** [comment]
you are correct, you give it the name and the class name of the thing annotated with `@ContentProvider`

So in your case it should look like `@TableEndpoint(name = ExamsProviderModel.ENDPOINT, contentProvider = MyDatabase.class)`

My models look like this:
![image](https://cloud.githubusercontent.com/assets/5386503/22308434/20f7d1dc-e304-11e6-8630-af9995acec1d.png)

**Comment by Chezlui** [comment]
Thanks @trevjonez that helped me to generate MyDatabase_Provider.java but now I'm blocked again.

I probably should know more about CP, nonetheless I even could implemented them in my code but I can not manage port them to DBFlow.

I feel like https://github.com/Raizlabs/DBFlow/blob/master/usage2/ContentProviderGeneration.md#connect-model-operations-to-the-newly-created-contentprovider is lacking details or is mixing examples due to the optional ways to implement the solution.

I wonder if a more detailed example could be proportioned.
Thank you all for your help.
