### ISSUE TITLE
How can I use alternative db file for android tests?

### ISSUE THREAD

**Issue by ssnake** [Raizlabs/DBFlow#1144]
Hi guys,

I need to know how to keep db file separately in production and test "environments". What I want:
1) in production it uses 'myapp.db'
2) in test it uses 'myapp_test.db'.

**Comment by xanscale** [comment]
use variable for name defined in buildConfigField

**Comment by xanscale** [comment]
https://www.google.it/search?q=android+sdk+buildConfigField&oq=android+sdk+buildConfigField&aqs=chrome..69i57j69i64l3.1124j0j7&sourceid=chrome&ie=UTF-8

**Comment by ssnake** [comment]
I'm expert in other  languages, but not in android yet. So, what I'm trying to achieve is whenever I launch JUnit test I need to use another filename of DB. My db is defined like this:

```
@Database(name = AppDatabase.NAME, version = AppDatabase.VERSION)
public class AppDatabase {

    public static final String NAME = "myapp"; // when I run unit test this name should be 'myapp_test'

    public static final int VERSION = 1;
}
```

**Comment by trevjonez** [comment]
My assumption is that you are trying to use a pre-populated database for your test. This can be accomplished easily if using Robolectric.

You can configure your robolectric test class with a custom application which also implements `org.robolectric.TestLifecycleApplication`

The method `beforeTest(Method)` is provided the test method that is about to be called.

By creating a custom annotation such as `@DBFileName("myapp_test.db")` you can then use reflection to access the annotation and value from the method inside of before test.

At this point you can copy the `myapp_test.db` file from wherever you put it (typically `src/test/resources` or similar) into the location provided to you when calling `getDatabasePath("myapp.db")`

in the `prepareTest(Object)` method initialize flow manager as you typically would in `onCreate`.

in the `afterTest` method do a `FlowManager.destroy()`


Now if my assumption is correct that you are trying to do this to have a prepopulated database for your tests is correct I would urge you to **STOP** what you are doing because the maintenance of your approach is much greater than just using your normal model classes. You may be better off just using a setup method annotated with `@Before` and populating the minimum viable data there.

This mechanism of coping databases is very useful for migration tests though and is encouraged in that case.

**Comment by ssnake** [comment]
I saw similar Robolectric approaches, but I want to use pure JUnit.
I've ended up in this because running JUnit & DBFlow mess database file that normally is used by application. Turned out android tests uses the same myapp.db that application uses. Thus after some numbers of running of application the data in myapp.db gets changed and this leads to fails in tests.
The solution is to use myapp.db for application and myapp_test.db for tests.
Hope I've made this clear.

**Comment by trevjonez** [comment]
so this is in the context of instrumentation tests that run on device?

**Comment by ssnake** [comment]
Yes

**Comment by ssnake** [comment]
Any ideas?

**Comment by agrosner** [comment]
1. Create a custom `FlowSQLiteOpenHelper` [here](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Databases.md#custom-flowsqliteopenhelper)
2. Copy paste `FlowSQLiteOpenHelper`. In the constructor:
```java
  public FlowSQLiteOpenHelper(DatabaseDefinition databaseDefinition, DatabaseHelperListener listener) {
        super(FlowManager.getContext(), databaseDefinition.isInMemory() ? null : databaseDefinition.getDatabaseFileName(), null, databaseDefinition.getDatabaseVersion());
``` 
Add a parameter for your flag for test:
```java
  public FlowSQLiteOpenHelper(DatabaseDefinition databaseDefinition, DatabaseHelperListener listener, boolean isTesting) {
        super(FlowManager.getContext(), databaseDefinition.isInMemory() ? null : (isTesting ?
 "test_" : "" ) + databaseDefinition.getDatabaseFileName(), null, databaseDefinition.getDatabaseVersion());
```
This should product a DBFile of `test_myapp.db`. Which is close enough to  Ithink what you want.

**Comment by ssnake** [comment]
Thank you. It works :+1:

**Comment by zmorris** [comment]
Updated link for FlowSQLiteOpenHelper:

https://agrosner.gitbooks.io/dbflow/content/Databases.html#custom-flowsqliteopenhelper
