### ISSUE TITLE
Date manipulation with sqlite wrapper language

### ISSUE THREAD

**Issue by SegoleneM** [Raizlabs/DBFlow#1159]
DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description: 

Hello,
I have a table with a property startDate (date) and a property nbDays (int) that represents a number of days. I'd like to query this table to get the rows where (startDate + nbDays) > today. Is there a way to achieve that with sqlite wrapper language ? 

I haven't found anything about adding days but I thought maybe adding an int would add milliseconds so I tried that:

`SQLite.select().from(MyTable.class)
  .where(MyTable_Table.startDate.plus(MyTable_Table.nbDays.multipliedBy(24*3600*1000)).greaterThan(today))`

However it doesn't build because multipliedBy expects a IProperty instead of an int.

Have you any idea on how to do what I want ?

**Comment by agrosner** [comment]
Try Wrapping the int in the PropertyFactory.from()

On Feb 2, 2017 11:56 AM, "SegoleneM" <notifications@github.com> wrote:

DBFlow Version: 4.0.0-beta5
Issue Kind (Bug, Question, Feature): Question

Description:

Hello,
I have a table with a property startDate (date) and a property nbDays (int)
that represents a number of days. I'd like to query this table to get the
rows where (startDate + nbDays) > today. Is there a way to achieve that
with sqlite wrapper language ?

I haven't found anything about adding days but I thought maybe adding an
int would add milliseconds so I tried that:

SQLite.select().from(MyTable.class) .where(MyTable_Table.
startDate.plus(MyTable_Table.nbDays.multipliedBy(24*3600*
1000)).greaterThan(today))

However it doesn't build because multipliedBy expects a IProperty instead
of an int.

Have you any idea on how to do what I want ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Raizlabs/DBFlow/issues/1159>, or mute the thread

**Comment by SegoleneM** [comment]
It works, thank you !
