### ISSUE TITLE
Simple Migrations as create new table with some column

### ISSUE THREAD

**Issue by MahdiPishguy** [Raizlabs/DBFlow#1178]
i trying ti find how can i create new table with this library Migrations, is any documentation or sample code to doing this action?

**Comment by TheWhiteLlama** [comment]
Nah I think there's only an AlterTable Migratin for adding new columns to your tables.
Since your java classes might change over your app's development time it probably could invalidate your migrations anyway.

I'd recomend either using sql files or custom Migrations for creating tables:

```
@Migration(version = 0, database = YourDatabaseClass.class)
public class TestMigrationextends BaseMigration {

    public TestMigration() {
        MigrationLoader.registerMigrationHandler(this);
    }

    @Override
    public void migrate(DatabaseWrapper database) {
        database.execSQL("CREATE TABLE IF NOT EXISTS `test`(`id`	INTEGER PRIMARY KEY AUTOINCREMENT);");
    }

}
```

As long as you're adding the annotation to your migration class and extend the BaseMigration you can perform any operations on your database. In this example the migration would run directly after your database has been created. (migration to version 0 before migration to 1)

Also have a look at these examples:
https://github.com/Raizlabs/DBFlow/blob/master/usage2/Migrations.md

**Comment by trevjonez** [comment]
Table creation happens automatically at the beginning of each migration. If it is only a new table just increment the DB version to trigger it.

**Comment by tux-world** [comment]
@trevjonez ok, so how can i trigger that after increment db version?

**Comment by trevjonez** [comment]
The next time the database is initialized it will compare the SQLite files version against the version your code says is latest. If it is different it will run migrations.

**Comment by tux-world** [comment]
@trevjonez after incrementing  database version on `AppDatabase.class` file and running application i get error, so this way i think dont work

**Comment by trevjonez** [comment]
What is the error and can you share the code you use to initialize DBFlow?

**Comment by tux-world** [comment]
@trevjonez this error: `Table does not exists`

**Comment by trevjonez** [comment]
You can see how the migrations are triggered by looking at [BaseDatabaseHelper.java](https://github.com/Raizlabs/DBFlow/blob/ad83cbacc0d945d5bae93bb05127804f83d22ab8/dbflow/src/main/java/com/raizlabs/android/dbflow/structure/database/BaseDatabaseHelper.java)

As you can see, in both  `onCreate` & `onUpgrade` the code first checks foreignkey support, then runs any necessary table creations, followed by any necessary migrations (files then class based).

So given the error you likely have an issue in either your configuration or initialization.

Please share the database class code, the new tables class declaration info, and the initialization code from your application class.

**Comment by tux-world** [comment]
@trevjonez ok, so please let me to check again that and share code if happening error, Thanks

**Comment by agrosner** [comment]
you should just add the table using DBFlow constructs + annotations. What are you trying to do? anything super custom?
