### ISSUE TITLE
Join tables with same column names causes missing data

### ISSUE THREAD

**Issue by DarkJaguar91** [Raizlabs/DBFlow#1271]
DBFlow Version: 4.0.0-beta7
Issue Kind (Bug, Question, Feature): Bug

Description: 
If you have 2 tables as follows:

Job
```
id - primary key
equipment - Foreign key object
description
```
Equipment
```
id - primary key
description
type - enum
```
When you write a joined query as follows:
```
SQLite.select().from(Job.class)
    .join(Equipment.class, Join.JoinType.INNER)
    .on(Job_Table.equipment_id.withTable().eq(Equipment_Table.id.withTable())
    .where(Equipment_Table.type.withTable().eq(<some type>))
    .queryList()
```
The Jobs are returned with the Description field as null.

The only way to fix it currently is to specify every field in the Job table in the query:
```
SQLite.select(
    Job_Table.id.withTable(),
    Job_Table.equipment_id.withTable(),
    Job_Table.description.withTable()
).from(Job.class)
    .join(Equipment.class, Join.JoinType.INNER)
    .on(Job_Table.equipment_id.withTable().eq(Equipment_Table.id.withTable())
    .where(Equipment_Table.type.withTable().eq(<some type>))
    .queryList()
```
I believe it could be a SQLite issue. I have not yet had time to override your code to determine a possible fix.

**Comment by trevjonez** [comment]
if you debug the process of unpacking the cursor what you will find is that the cursor will have all the columns from both tables without any sort of disambiguation. what you are doing to disambiguate them is mostly correct although there is an easier way.

I would recommend adding the following to each of your table classes:
```java
public static final IProperty STAR = new Property(User.class, NameAlias.rawBuilder("*").build()).withTable();
```

This will give you the same result of specifying every column with much less work at in the query.

```java
SQLite.select(Job.STAR)
      .from(Job.class)
      .innerJoin(Equipment.class) //I recommend you use the inner join method so these things read more like sql
      .on(Job_Table.equipment_id.withTable().eq(Equipment_Table.id.withTable())
      .where(Equipment_Table.type.withTable().eq(<some type>))
      .queryList()
```

**Comment by DarkJaguar91** [comment]
Thanks @trevjonez that does indeed make it a lot easier.

I am willing to close this ticket with that answer, however it may be prudent to add the "STAR" variable you have made to the generated _Table class for each domain object. Currently it has a variable for all columns, but that variable does not have the table name prefixed.

**Comment by trevjonez** [comment]
I don't have a current project available that uses dbflow to actually view the generated code(recent change of employment). can you copy here the all columns variable that you speak of? there may be a way to make that work cleanly rather than having to add anything.

If you are using kotlin you can use an extension method to produce this thing.
```kotlin
fun KClass<*>.STAR(): IProperty {
    return Property(this.java, NameAlias.rawBuilde("*").build()).withTable()
}
```

consumption would be `User::class.STAR()`

**Comment by DarkJaguar91** [comment]
Sadly my company and the client will not let me write the code in Kotlin, all though I wanted to.

The current Job_Table generation class would generate the following global variable for all columns:
```
public static final IProperty[] ALL_COLUMN_PROPERTIES = new IProperty[]{id,description,equipment_id};
```

I will look into changing the code generation tool tonight/tomorrow morning. And possibly make a pull request.

Out of curiosity. Would it not be a good assumption to assume the first duplicate field found in the cursor is the field for the Table you are searching in?

**Comment by trevjonez** [comment]
It would probably take a TON of research to figure out if it is deterministic in order across all devices, plus there is probably no guarantee it won't change in the future. PLUS if you are only selecting a subset of the columns I would imagine there are perf improvements as a result of only selecting what you need.

Adding another static property to the generated table class like the one I shared earlier is probably the easiest approach to this and would be super simple to implement in the generator since the only thing it needs to know about is the table class.

**Comment by DarkJaguar91** [comment]
@trevjonez I have made some changes to generate the STAR field in the generated TABLE classes and opened the following pull request: #1273 

I did not append `.withTable()` as the user then has the option to use the table name or not. You input on that would be appreciated as it is technically already a star operator with just the plain `.select()` call.

Also, I have the `.rawBuilder("*").build()` in plain text. Is there a better way to add that? I don't have much experience with the _javapoet_ library.

**Comment by trevjonez** [comment]
looks pretty darn good. I responded directly on the pr with details so as to keep the implementation details with the code.

**Comment by agrosner** [comment]
I think a safer way is to not generate it  but provide a static method for Star because it would get generated for every table. If you don't use it, then it is just generated for nothing. I will use @trevjonez method by providing both a static method and Kotlin extension method. 
Itll look like this:
```java
Property.allProperty(MyTable.class)
```

and in Kotlin it will look like:
```kotlin

inline fun <reified T: Any> KClass<T>.allProperty() = Property.allProperty(this)

```
