### ISSUE TITLE
AlterTableMigration to add column throws compile-time error

### ISSUE THREAD

**Issue by strapp342** [Raizlabs/DBFlow#1363]
DBFlow Version: 4.0.4
Issue Kind (Bug, Question, Feature): Question

Description: 
I have a table that I want to add a column to. I added the column in the Model class and added the below class to my Database class.

`@Migration(version = WizardryDatabase.VERSION, priority = 0, database = WizardryDatabase.class)
    public class Migration3 extends AlterTableMigration<Bibliography> {

        public Migration3(Class<Bibliography> table) {
            super(table);
        }

        @Override
        public void onPreMigrate() {
            super.onPreMigrate();
            addColumn(SQLiteType.TEXT, "test");
        }
    }`

However, I am getting this error when compiling:
`Error:(18, 21) error: an enclosing instance that contains WizardryDatabase.Migration3 is required`

I have incremented the version number in the Database class.

**Comment by agrosner** [comment]
make the inner class `static`. it appears you're making it inner.

**Comment by strapp342** [comment]
That solved the issue. Closing as resolved.

**Comment by AllanWang** [comment]
What is bibliography in your case? The old model? The new model?

**Comment by strapp342** [comment]
Bibliography is the existing model that I am adding a column to.

**Comment by AllanWang** [comment]
Would that mean that you need to keep old models every time you il update the dB so you can reference it in the db? And I'm wondering if it's necessary or if that's part of the structure where it's add only, since the new model might be usable as well. I still have to test my main migration but I will report back

**Comment by strapp342** [comment]
I'm not sure what you're asking. My migration is simply adding a column to an existing model. I don't have any models in my code that are not being used. What are you trying to do?

**Comment by AllanWang** [comment]
@strapp342 
let's say that you have a database that uses `ModelA`.

You now want to add a column (in your case test), so you'll have a new model called `ModelB`.

Are you passing in `ModelA` to the migration or passing in `ModelB`?

I'm not too familiar with the inner working on the migration, which is why I think all of them should work since both models can be created with the existing data. But then I'm not sure why a model needs to be passed to begin with, but that's probably beyond my knowledge of what is happening.

**Comment by strapp342** [comment]
Ah, I see. So in the case where you are simply adding a column, a new model is not being created. 

Example:
You have `ModelA` with columns `A`, `B`, and `C`. You want to add a new column `D` in `ModelA`.  The steps you would go through to add the new column are to add the new column to the model in your code, then build the Migration class that adds the column (this is the code that I have above). The end result is `ModelA` will have columns `A`, `B`, `C`, and `D`. There is no automatic creation of `ModelB`.

Hope this helps.

**Comment by AllanWang** [comment]
@strapp342 

Thanks a lot. For those who were confused like me, here is my example with Kotlin:

```kotlin
@Database(name = NotificationDb.NAME, version = NotificationDb.VERSION)
object NotificationDb {
    const val NAME = "Notifications"
    const val VERSION = 2
}

@Migration(version = 2, database = NotificationDb::class)
class NotificationMigration2(modelClass: Class<NotificationModel>) : AlterTableMigration<NotificationModel>(modelClass) {
    override fun onPreMigrate() {
        super.onPreMigrate()
        addColumn(SQLiteType.INTEGER, "epochIm")
        L.d("Added column")
    }
}

@Table(database = NotificationDb::class, allFields = true, primaryKeyConflict = ConflictAction.REPLACE)
data class NotificationModel(@PrimaryKey var id: Long = -1L, var epoch: Long = -1L, var epochIm: Long = -1) : BaseModel()
```

where `NotificationModel` didn't have `epochIm` in version 1.

Make sure to also change the versions, since that was my mistake for the past little while...
