### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by sigfridod** [Raizlabs/DBFlow#1387]
DBFlow Version:
Issue Kind : Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 

Going through documentation of caching found below 

> Caching should be avoided (or clear caches) when:
Performing selection, complex queries, anything different than starting with SQLite.select()
Using the wrapper modifications such as Insert, Update, or Delete. In this case you should clear the associated cache, post-operation

If during insert update or delete we should clear cache than how cache is benefit for ?
if model is get delete or update from database so the cache should be.
If i am getting it wrong pls correct me or suggest me of using caching models

thanks

**Comment by agrosner** [comment]
caching is useful for Model operations. when you use wrapper operations, we have no efficient way to know what has changed and adjust caches. So safest is to clear post operation, otherwise you will be left will stale data. Caching is great for loading same set of model objects over and over again that rarely change. otherwise you dont need caching as reads can be pretty fast unless you're also writing to DB at same time.

**Comment by harsukhnitor** [comment]
FlowManager.getModelAdapter(table).getModelCache().clear()
