### ISSUE TITLE
Class Not found. I am trying to make simple demo app using DBFlow in Eclipse

### ISSUE THREAD

**Issue by hemangN** [Raizlabs/DBFlow#140]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder

@ mDatabaseHolder = (DatabaseHolder) Class.forName("com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder").newInstance();

**Comment by agrosner** [comment]
are you using the `apt` plugin?

**Comment by HemangNirmal** [comment]
@agrosner  thanks for quick reply 
I have enabled project specific annotation processing and also added DBFlow lib in path. Here I am adding whole error stack 

03-13 11:09:59.159: E/AndroidRuntime(2468): FATAL EXCEPTION: main
03-13 11:09:59.159: E/AndroidRuntime(2468): Process: com.example.dbflowpro, PID: 2468
03-13 11:09:59.159: E/AndroidRuntime(2468): java.lang.RuntimeException: Unable to create application com.example.dbflowpro.DbFlowApp: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.os.Looper.loop(Looper.java:135)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.reflect.Method.invoke(Native Method)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
03-13 11:09:59.159: E/AndroidRuntime(2468): Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:110)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at com.raizlabs.android.dbflow.config.FlowManager.init(FlowManager.java:148)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at com.example.dbflowpro.DbFlowApp.onCreate(DbFlowApp.java:14)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	... 9 more
03-13 11:09:59.159: E/AndroidRuntime(2468): Caused by: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.Class.classForName(Native Method)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.Class.forName(Class.java:308)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.Class.forName(Class.java:272)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseHolder(FlowManager.java:108)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	... 13 more
03-13 11:09:59.159: E/AndroidRuntime(2468): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder" on path: DexPathList[[zip file "/data/app/com.example.dbflowpro-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-13 11:09:59.159: E/AndroidRuntime(2468): 	... 17 more
03-13 11:09:59.159: E/AndroidRuntime(2468): 	Suppressed: java.lang.ClassNotFoundException: com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
03-13 11:09:59.159: E/AndroidRuntime(2468): 		at java.lang.Class.classForName(Native Method)
03-13 11:09:59.159: E/AndroidRuntime(2468): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-13 11:09:59.159: E/AndroidRuntime(2468): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-13 11:09:59.159: E/AndroidRuntime(2468): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)


03-13 11:09:59.159: E/AndroidRuntime(2468): 		... 18 more
03-13 11:09:59.159: E/AndroidRuntime(2468): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by agrosner** [comment]
Sorry I misread this issue. Eclipse is not supported. Not sure if you have a choice, but Android Studio is now the official IDE for Android development and I don't believe Eclipse will be supported much longer by google.
