### ISSUE TITLE
How to use different database dynamically？

### ISSUE THREAD

**Issue by SailFlorve** [Raizlabs/DBFlow#1408]
My app allows different users to login, I want that each user use database named by their username. Morever, when no user login, no database used. Call flowmanager.init in Application class can't realize my demand.

**Comment by agrosner** [comment]
its not documented yet but 4.1.0 will have support for such a feature. If you use latest develop commit (38fe8f0cd6) as your version you can try this out.

You need to add your db name dynamically as `@Database(name = )` will be deprecated in favor of specifying name:
```
FlowManager.init(FlowConfig.Builder(RuntimeEnvironment.application)
                    .addDatabaseConfig(DatabaseConfig.builder(SomeDB::class.java)
                        .databaseName("content")
                        .build())
                    .build())
```
then when you need to change the DB dynamically you can use:
```
FlowManager.getDatabase(MyDB::class.java).reset(...) // DBConfig.builder() with new name here
```
this will delete the previous database and reopen with the new config. just be careful on app restarts as you will need to ensure you open the proper dbconfig, otherwise you can end up with multiple dbs on disk.

**Comment by laycui** [comment]
Is there a way that I can switch from one DB to another with different names, but the data is not deleted? Just close one DB and open another?

This usage case is happened when user switching account in the same app:
When user switch account from A to B (ex, Gmail), the DB-A is closed but data is not deleted, while DB-B is open and the data on it is not reset.

I have written a demo app using the logic in thread 2, both of the DBs are reset :(

**Comment by wangsuicheng** [comment]
@laycui  you can copy the old db to a name.tmp.db before deleting?
