### ISSUE TITLE
Ability to load a database dynamically by name *without* resetting/deleting existing one?

### ISSUE THREAD

**Issue by c0state** [Raizlabs/DBFlow#1449]
DBFlow Version: 4.1.1
Issue Kind: Question (and possiblyFeature):

Description: 
Starting in DBFlow version 4.1.0, there is the ability to dynamically load another database file via a `FlowManager.getDatabase(MyDatabase.class).reset(...)` call. However, this method deletes the existing database. Is there a way (or something planned) to load another database but leave the existing one intact?

The use case I have is an app with a catalog of "products" that the user can select. Each product has a database associated with it where the model is the same across products. Upon selection of a particular product, I'd like to dynamically load said product. Only one product is active at a time.

**Comment by baranowskinet** [comment]
DBFlow Version: 4.1.1
Issue Kind: Bug & Question

Maybe this should be raised as other issue but this is related to above question.
With new way of init database (no more annotation for name) there is a problem when user want to open another database. I have two databases and I separately opening them as I am also using SqlCipher and to open second db I need to know password. When I call second time FlowManager.init(..) system already has cached all my db definitions and it is using cached empty definition. Result of it is that second db has default CalssName.db db file name instead of what I want to pass in second init. Solution for it is add all possible config in first init but still I need to call init to pass specific password via openHelper.

I would like to have possibility o manage each db individually based on database name not by class. Ability to close db without delete database, open new/existing database which are based on the same class but has different names. Purpose: multi-database system when each user has own db encrypted with own password but used the same class including the same migrations scripts.

**Comment by carmas123** [comment]
+1

**Comment by agrosner** [comment]
in `develop` for 4.1.1. call `database<MyDatabase>().reopen(newConfig)` if you're Kotlin consumer. otherwise use `FlowManager.getDatabase(...).reopen(newConfig)`
