### ISSUE TITLE
What is the difference between BaseModel save() and update()?

### ISSUE THREAD

**Issue by Rainer-Lang** [Raizlabs/DBFlow#151]
If I have saved a model with save() and then change the attributes so I can also use save() again. No need for update().

**Comment by agrosner** [comment]
`update()` will force an update on the table first. If that fails, it resorts to an `insert()`.

 A `save()` will check using `ModelAdapter.exists(Model)` first before inserting or updating. This is more efficient for `Column.COLUMN_PRIMARY_KEY_AUTOINCREMENT` because it simply checks the autoincrementing key on the model if its not null and larger than 0. If its not an AI PK, then it uses its `ModelAdapter.getPrimaryWhere(Model)` to see if it exists.

I hope this helps.

**Comment by agrosner** [comment]
an `update()` is much more efficient in large quantities than a `save()` if you know the data already exists.

**Comment by Rainer-Lang** [comment]
@agrosner Thank you for explanation.

**Comment by Rainer-Lang** [comment]
Maybe this is something for the wiki.
