### ISSUE TITLE
What is right way to update prepackaged database that is read-only

### ISSUE THREAD

**Issue by rokos** [Raizlabs/DBFlow#244]
I have prepackaged database in assets folder that gets update once in a while. If i put new database (new rows are added ) in assets foder this doesnt get copied and i end up with old database. I tried using Migration and increasing version, but new database doesnt get copied.

**Comment by agrosner** [comment]
did you place it in `assets/{DatabaseName}.db` ? That's what it looks for. It must have gotten removed from README docs when It went 2.0.

**Comment by agrosner** [comment]
The prepackaged database only gets copied on creation of the database. If you wish to copy the new file from assets directory into your database after that, you could define a class in the same package as the `BaseDatabaseDefinition`, access the object by using `FlowManager.getDatabase()` and return the `FlowSQLiteOpenHelper` object to `movePrepackagedDB()` from the assets to the app DB. The reason I don't expose this is because this can lead to IO errors, SQLiteExceptions, and issues with concurrency. When you have pending access to the DB, this becomes problematic.

**Comment by arso8** [comment]
Or you can delete DB `getDatabasePath().delete()` before `FlowManager.init(this)` yourself. New version will be copied from assets.
