### ISSUE TITLE
what's the dbflow proguard rule?

### ISSUE THREAD

**Issue by jiqimaogou** [Raizlabs/DBFlow#248]

**Comment by agrosner** [comment]
Haven't tested Proguard to work with this library. Ensure all `@Column` and `@Table` classes provide the `name()` / `tableName()`property so the database is correctly referenced. Then add this line:

```-keep class com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder```

Not even sure that works but its a good start and maybe we can figure out the _actual_ solution so I can post it in the README.

**Comment by agrosner** [comment]
If anyone used it and can speak to it, that would be __GREAT__

**Comment by martino2k6** [comment]
I recently switched one of my projects which is Proguard'ed to use DBFlow, but haven't gotten as far as doing a release build with the changes. Will try to provide details once I'll be a bit smarter myself, providing no one else gets to take a look at it first.

**Comment by kenkyee** [comment]
Most likely you don't have to do much...DBFlow's class generation is done at compile time.  Most issues w/ annotations happen if they do runtime reflection of names.

**Comment by agrosner** [comment]
Yep @kenkyee thanks. I believe then its just simply:

```
-keep class com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder

```
Since thats the only class that's looked up by reflection.

**Comment by agrosner** [comment]
closed works as intended.

**Comment by grennis** [comment]
Actually if you use GSON to serialize any DBFlow model, you get exception like this

java.lang.IllegalArgumentException: com.raizlabs.android.dbflow.d.c.c<MyClass> declares multiple JSON fields named a

I'm not sure where the problem is. The only way I can workaround it for now is:

    -keep class com.raizlabs.android.dbflow.** { *; }

**Comment by MGasztold** [comment]
I try to obfuscate a project that uses DbFlow database and i encounter a following issue with Dexguard:

```Warning: com.raizlabs.android.dbflow.config.DbHelper_Database: can't find referenced field 'java.util.List models' in program class com.raizlabs.android.dbflow.config.DbHelper_Database
Warning: com.raizlabs.android.dbflow.config.DbHelper_Database: can't find referenced field 'java.util.Map modelTableNames' in program class com.raizlabs.android.dbflow.config.DbHelper_Database
Warning: com.raizlabs.android.dbflow.config.DbHelper_Database: can't find referenced field 'java.util.Map modelAdapters' in program class com.raizlabs.android.dbflow.config.DbHelper_Database
Warning: com.raizlabs.android.dbflow.config.DbHelper_Database: can't find referenced field 'java.util.Map modelContainerAdapters' in program class com.raizlabs.android.dbflow.config.DbHelper_Database```

My dexguard-project.txt fragment about dbflow:
```
-keep class com.raizlabs.android.dbflow.config.** {
  *;
}
-keepclassmembers class com.raizlabs.android.dbflow.config.DbHelper_Database {
  *;
}
```
I have checked my output jar and in fact these fields are not there. Any idea? Thanks.

**Comment by kenkyee** [comment]
So FYI, I finally had to do obfuscation on a project w/ DBFlow.  I had to do this:
-keep class com.myproject.db.models.** { *; }
As well as:
-keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }
-keep class com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
-keep class * extends com.raizlabs.android.dbflow.config.BaseDatabaseDefinition { *; }

The problem is when the shadow classes for models are generated, they seem to be dependent on the previous class' name (fairly common w/ compile time code generators) so you have to keep the names the same.

The other classes seem to be referenced directly by the compiled core code by name, so if you obfuscate them, they can't be found.

This is all for DBFlow 2.x.  I haven't switched to DBFlow 3.x yet but will update you guys when I do.
