### ISSUE TITLE
Migration support for adding new Table

### ISSUE THREAD

**Issue by simernes** [Raizlabs/DBFlow#324]
Can you please add this, and add it to the doc? To be clear: the ability to write migrations for adding new tables. As far as I could find out it's not possible yet, but if it is please do point me in the right direction =)

Thanks

**Comment by mroczis** [comment]
Hey,
I was trying to figure out how to create table in an existing database and here's my solution

@Migration(databaseName = Database.NAME, version = 2)
public class DatabaseVersion2 extends BaseMigration {

    @Override
    public void migrate(SQLiteDatabase sqLiteDatabase) {
        NewTable$Adapter adapter = new NewTable$Adapter();
        sqLiteDatabase.execSQL(adapter.getCreationQuery());
    }
}

**Comment by agrosner** [comment]
@simernes @mroczis not a bad idea at all. I guess if I added a ` version()` to the `@Table` class, it could defer the creation of the table until the specified version. For now that hack appears to work, for `3.0` I will add the ability to do so. (Im going to rewrite the processor and clean some things up).

**Comment by ervinsae** [comment]
Thank you it is very useful

**Comment by grennis** [comment]
I dont understand why this code is considered a hack? Seems like a proper solution to me - a CreateTableMigration would look just like that, would it not? Also I dont understand comment "defer creation of table until specified version". It seems maybe the behavior of table creation has changed since that comment - in my tests, tables are only automatically created on first time install (which is desired behavior I think). Then create table migrations work as expected. Or I am completely off track here?

**Comment by agrosner** [comment]
closing. migration for adding tables happens automatically on DB upgrade.
