### ISSUE TITLE
Gson with Models

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#468]
I want to create a json from a model with Gson. 
Is it possible to save the reference id instead of the whole Object for ForeignKey?

If the model contains another model Gson will deserialize it as well.

**Comment by agrosner** [comment]
yes, in `ForeignKey` annotation, there's a method called `saveForeignKeyModel()`

**Comment by agrosner** [comment]
you need to convert the field you're saving into a `ForeignKeyContainer`

**Comment by agrosner** [comment]
https://github.com/Raizlabs/DBFlow/blob/develop/usage/GettingStarted.md#the-ant-table--1-to-many for an example using 3.0

**Comment by noinnion** [comment]
great thanks, I will look into it.

**Comment by TwRlx** [comment]
GSON + ForeignKeyContainer doesn't work.
Because ForeignKeyContainer contains modelAdapter and modelContainerAdapter, and can contain model and relationshipModel.

What i want is when Gson writes object to json, it should store only Map<String, Object> data from ForeignKeyContainer. And on restore from json it recreates with this data and default adapters.

I think i can do it only with custom Gson TypeAdapterFactory with TypeAdapters.
Or it'll be better way for me to use only reference id fields and everything will be simple.
