### ISSUE TITLE
Ignore local columns if not in source JSON model when updating

### ISSUE THREAD

**Issue by marwfair** [Raizlabs/DBFlow#490]
I have a Book model that has a local boolean field "hasRead". The user can update this field on the device. However, when I hit the api to update the Books on the device, hasRead always gets set back to false. Is it possible ignore a field when updating if it is not in the JSON model?

I am using Jackson to parse my JSON, but using @JsonIgnore on the hasRead field so it is not getting set when parsing the JSON.

**Comment by agrosner** [comment]
Is this a DBFlow question?

**Comment by marwfair** [comment]
@agrosner Yes. Currently, every time I fetch all of the Books from the api, I have to do a db query on each object to see if it already exists, then assign the "hasRead" field to the new Book before saving it to the db. If I don't do this, "hasRead" always gets sets back to false because that field does not come from the api. Does DBFlow have a way of updating my Book object without overwriting fields that aren't given?

**Comment by krzysiek-zgondek** [comment]
Well i think i got something similar. It would be great if there was some sort of way to have 
new Update(Table.class).all(boolean).from(Model).where(Conditions).
'all' would take all fields from 'from' which are or aren't nulled (based on boolean argument) and update all table rows based on 'where' conditions.

Because right now, every time when i change something in Model i have to change related queries.
It would be a great addition to have it just inside lib.

**Comment by agrosner** [comment]
This is not supported, since we require all fields pretty much when inserting, updating, or deleting models. For insert statements in particular, we use a `SQLiteStatement` which is precompiled for performance that requires all fields to be present. Not as flexible as `ContentValues`
