### ISSUE TITLE
Missing generated classes in build/apt/debug

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#525]
When my project is set to build in debug mode, I cannot import the generated `*_Table`, `*_Adapter`, etc. classes. Looking at `build/apt/`, I only see these classes built in release and not in debug.

When I set my project to build in release though, I'm able to import those classes.

Any ideas how to fix this?

**Comment by re3lex** [comment]
Almost same here: suddenly dbflow stopped generating any *_Table, *_Adapter, etc. sources though it was working well 1 month before. Build type change is not helping.

I'm using version control system and I'm sure gradle config was not changed

**Comment by brwskitime** [comment]
I have almost the same isssue. I  have about 20 tables, and it only generates 4 and sometimes 5 of the _Table classes.

**Comment by re3lex** [comment]
@brwskitime I have found one workaround. I have moved all models (only models) to separate module within project and anything now works fine for me.
Except DBFlow I'm using Parceler library which is generating sources during compile time like DBFlow and before I had issues with it too. But now everything is working fine.

I guess this issue is not with DBFlow but with library that is generating sources.

**Comment by brwskitime** [comment]
I believe @re3lex just mentioned this, but discovered a fix. I had an abstract parent model to hold the primary key, and then all the real models/tables in a sub-package. Turns out when I moved my abstract class down to the same package as the rest, the problem went away. 

Short story, keep all of your models in the same package!

**Comment by arriolac** [comment]
@re3lex & @brwskitime I have all of my models (subclasses & superclasses) within the same module and still running into this problem.

**Comment by re3lex** [comment]
@brwskitime looks like this is not my case but another one.
Thanks for highlighting it.

**Comment by re3lex** [comment]
@arriolac try to move models into separate saying Models module hwere only models are put.
add into Models module gradle build only libraries your models depend on.
I hope this can help you (That helped me)

**Comment by arriolac** [comment]
Didn't make any change but my errors went away after i updated to gradle 2.10 and build tools to 2.0.0-alpha5.

**Comment by arriolac** [comment]
Still running into this issue actually. I believe the issue is related to gradle's incremental build. See related issue: https://github.com/google/dagger/issues/298

**Comment by Ajay-Jadhao** [comment]
Any update on this issue?
