### ISSUE TITLE
cannot find symbol class and package does not exist

### ISSUE THREAD

**Issue by DoubleTime** [Raizlabs/DBFlow#533]
I just move to 3.0 beta1.

I have a package name DB and put all database related files inside the package.
Pre 3.0 I have no trouble, but now when I try to compile the auto generated code at ../app/build/generated/source/apt/.. 
Will produce this 2 error 
Error:(5, 32) error: cannot find symbol class DB
Error:(18, 70) error: package DB does not exist

Is there any solution for this?

**Comment by Inso123** [comment]
Hi, 

I'm also using the latest beta and got the same issue. Once I moved the database table classes to the root package, it compiled perfectly.

**Comment by amugox** [comment]
I am having the same issue! any help?

**Comment by DoubleTime** [comment]
@amugox Like Inso123 mention, move all database related class to the root package. 
Hope they fix it soon, the directories are kinda messy now.

**Comment by amugox** [comment]
@DoubleTime Thanks! it works only that my classes look disorganized

**Comment by agrosner** [comment]
I need more information. Not sure what this means and I'm using 3.0+ in a few apps and no issues in regards to that.

**Comment by Inso123** [comment]
Not sure what changed in the latest commit but it seems to be fixed now. I was about to create an example application to show the issue. It compiled just fine now. Even in my application, not the example applicaton. 

I got the errors if I put the database related files to their own package. See picture below: 

![unbenannt](https://cloud.githubusercontent.com/assets/7069491/12221065/61a3cc4e-b78c-11e5-9756-4450f3df4e03.PNG)

As I can't reproduce the issue anymore, I'm not able to give you a more detailed output. Maybe DoubleTime can.

**Comment by DoubleTime** [comment]
I add screenshot for the error I faced

<img width="948" alt="error" src="https://cloud.githubusercontent.com/assets/5257978/12285104/976448ba-b9f1-11e5-816a-112ec4326c74.png">

**Comment by blcooley** [comment]
I'm having the same problem even with the latest commit. I can reproduce it in the sample app (found in DBFlow/app) as follows:

1) clone the project (git clone https://github.com/Raizlabs/DBFlow.git)
2) Create a subdirectory under the directory app/src/main/java/com/raizlabs/android/dbflow (To follow this issue, I called it DB).
3) Move all the model files to the new subdirectory
4) For the model files that moved in step 3, update their packages to reflect the new directory (i.e., add .DB to the end of the package name in this case)
5) Attempt to run the project.

Following these steps,I get an error in the generated source code. For example, there is a source file called SecondAppDatabaseSecondApp_Database.java which contains an import statement as follows:

import com.raizlabs.android.dbflow.DB;

And the error is "Cannot resolve symbol 'DB'"

I am unsure if the issue is related to moving the files. I encountered this issue in my own project after refactoring (using the Refactor/Move... feature in Android Studio 2.0 Preview 4) to move the files from the root package to a sub package.

**Comment by astrobread** [comment]
Keep the package names lower-case. I ran into this issue when restructuring my test project into a more organized layout. When I refactored the new folder names to be all lower-case, the problem went away. I can even reverse it and recreate the issue again.

Look at the above screenshots, all the ones that are working use "db", while the ones that fail use "DB" as the package name.

**Comment by blcooley** [comment]
@astrobread This exactly describes the symptoms I saw. The package name I was using when I got the error was "Model" but I currently have it working correctly with a package called "model"

**Comment by mplacona** [comment]
I totally had this same issue and fixed it by changing the package names to lowercase. +1 to @astrobread

**Comment by DoubleTime** [comment]
Thanks so this is the reason !

**Comment by ktzouno** [comment]
Identifying the package-part based on the Java convention for lower-case package names is quite poor technique IMHO.

**Comment by mayank-kgp** [comment]
I am using the same issue.
