### ISSUE TITLE
[3.0.0-beta2] defaultValue not generated

### ISSUE THREAD

**Issue by noinnion** [Raizlabs/DBFlow#565]
I think defaultValue is not generated

```
	@Expose
	@PrimaryKey
	public int id;

	@Expose
	@Column
	@NotNull
	public String name;

	@Column
	public String passwordHash;

	@Expose
	@Column(defaultValue = Role.DEFAULT_ROLE)
	public String role;

	@Column(defaultValue = "0")
	public long lastLoggedIn;

	@Column(defaultValue = "1")
	public boolean enable;
```

it only generates

```
  @Override
  public final String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS `User`(`id` INTEGER,`name` TEXT NOT NULL,`passwordHash` TEXT,`role` TEXT,`lastLoggedIn` INTEGER,`enable` INTEGER, PRIMARY KEY(`id`)" + ");";
  }
```

**Comment by astrobread** [comment]
I've noticed the same issue as well. The defaultValue isn't added to the CreationQuery, and when I save a record that has defaultValue columns, they don't behave any differently. If you don't touch the column, it is stored and retrieved as null from the database instead being populated with the defaultValue.

**Comment by agrosner** [comment]
fixed in `develop`. Only non-primitive basic types are supported, since primitives always hold a value. `Model` or `ModelContainer` fields are not supported.

**Comment by agrosner** [comment]
it will only place the value if missing from the query.

**Comment by noinnion** [comment]
what are non-primitive basic types?
I have problems with beta5

**Comment by zmorris** [comment]
This is still broken as of 3.1.1, not sure if it's been fixed in 4+.

    @Column(name = "my_column", defaultValue = "0")
    Boolean myColumn;

Expected table creation syntax after initial migration:

    CREATE TABLE IF NOT EXISTS `my_table`(`my_column` INTEGER NOT NULL DEFAULT '0');

Actual table creation syntax verified from MyTable$Adapter:

    CREATE TABLE IF NOT EXISTS `my_table`(`my_column` INTEGER NOT NULL);

This is particularly devastating because due to **the primary bug/feature of SQLite that table columns can't be updated or dropped**, there is no easy way to fix this manually either after creation or in a subsequent migration.  More info:

https://stackoverflow.com/a/805375/539149

http://www.sqlitetutorial.net/sqlite-alter-table/

I've lost a day to this so far and am expecting to lose at least several more.
