### ISSUE TITLE
lazy load relations tables

### ISSUE THREAD

**Issue by morder** [Raizlabs/DBFlow#601]
I want to load many rows from table A which have relation to some table B

I'm tried use 
@Column
    @ForeignKey(...)
public ForeignKeyContainer<SomeClass> relation;
and 
@Column
    @ForeignKey(...)
public SomeClass relation;

but, it generates calls in first case:
A_Adapter -> reloadRelationships -> queryModelContainer -> ... sql query to table B with id == `column number`

in second case 
A_Adapter -> loadFromCursor -> querySingle-> .. and again query to table B...

So, how can I load all rows from A but do not actively load all relations from table B ?

**Comment by astrobread** [comment]
AFAIK, the only way to prevent a one-to-one relationship from loading is to manually specify your Select() parameters. If you select every field except the foreign key relation_id, then it will be left NULL and table B can't be queried. The downside is that I'm pretty sure saving afterwards would break the relationship.

I'm halfway hoping someone will chime in that I'm wrong and there's a better method, but that's all I've found so far.

**Comment by morder** [comment]
But I want to load foreign key relation ID
For now I used a caching, so it reduced query time, but still query performance is relatively slow

**Comment by astrobread** [comment]
According to https://github.com/Raizlabs/DBFlow/blob/master/usage/ModelContainers.md ForeignKeyContainer is supposed to be lazy-loading, but that's clearly not the case. 

In a 25k record save/load experiment, simply having a relation_id that was not null increased my select query time from 3 seconds to 100 seconds. Instead of one query for 25k records, it becomes that PLUS an additional 25k SQL queries against the related table. 

If this is a deal breaker, until it gets fixed you can awkwardly work around the issue like I mentioned in my previous post, or you can abandon using ForeignKeyContainer and just handle them manually somehow.

**Comment by agrosner** [comment]
yes it looks like it's not actually taking advantage of the `ForeignKeyContainer` aspect in the newest version. This appears to be a valid bug.

**Comment by agrosner** [comment]
will have to rework it to load only the keys into the container

**Comment by agrosner** [comment]
now working in develop, try it out! :)
