### ISSUE TITLE
How to prevent circular queries

### ISSUE THREAD

**Issue by arriolac** [Raizlabs/DBFlow#615]
I have 2 tables that both have foreign keys against each other. A `User` can have many `Address` instances but can only have one default `Address` instance. See scheme below.

```
@ModelContainer 
@Table(database = Database.class) public class User extends BaseEntity {

    @NotNull @Column 
    String name;

    @ForeignKey(saveForeignKeyModel = false)
    Address defaultAddress;
}

@ModelContainer 
@Table(database = Database.class) 
public class Address extends BaseEntity {

    @Column 
    String street;

    @Column 
    @ForeignKey(saveForeignKeyModel = false) 
    User user;
}
```

This schema produces a circular query. Any ideas how to address this?

**Comment by agrosner** [comment]
yes. You need to have one of them use a `@ForeignKeyContainer` object in order to properly prevent circular queries. Or use a primitive value object as the `ForeignKey` object with its table it references specified in the annotation.

There was an issue where I was querying full object of a `ForeignKeyReference`, which has thus been fixed in `develop`. soon 3.0.0-beta3 will be released with this fix. If you need it now, Id recommend grabbing the latest 10-digit commit hash in `develop`.

**Comment by arriolac** [comment]
Yeah, I tried having one relationship as a `@ForeignKeyContainer` before I posted this but still got in an infinite query loop, I'm on `3.0.01-beta1`. Will wait for the `3.0.0-beta3` release which should address that. Thanks!

**Comment by arriolac** [comment]
`3.0.0-beta3` released.
