### ISSUE TITLE
autoincrement=true

### ISSUE THREAD

**Issue by bonefishky** [Raizlabs/DBFlow#628]
When using autoincrement on a primary key field 

example: 

```@PrimaryKey (autoincrement=true)
long id;```

it appears the counter is getting reset when items are deleted. In other words, available ID's lower than the MAX ID in a table are being re-used. It appears DB flow is managing its own internal autoincrement value?

In a scenario of insert record a, b, c.  Their IDs become 1,2,3 respectively.  If I remove item c and add item d I would expect item d's ID to be 4, but its not, its 3.    

Is this the desired behaviour?

**Comment by agrosner** [comment]
can you send me an example of your `Model` class? We are simply at the base, using the standard Android SQLite methods. For insert statements, we're calling `SQLiteStatement.executeInsert()`, for updates we're using the:
```
long count;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.FROYO) {
            count = database.updateWithOnConflict(tableName, contentValues, where, whereArgs, conflictAlgorithm);
        } else {
            count = database.update(tableName, contentValues, where, whereArgs);
        }
        return count;
```
methods

**Comment by bonefishky** [comment]
Here is an example of the class. Appreciate you looking into this..  

To remove (delete) I just call `someInstance.delete();`

If I remove all items in the table, the next insert starts with an ID of 0.

`package com.fish4fun.myapp.models;

import android.util.Log;

import com.raizlabs.android.dbflow.annotation.Column;
import com.raizlabs.android.dbflow.annotation.ModelContainer;
import com.raizlabs.android.dbflow.annotation.PrimaryKey;
import com.raizlabs.android.dbflow.annotation.Table;
import com.raizlabs.android.dbflow.structure.BaseModel;

import java.io.File;

@ModelContainer
@Table(database = MyAppDatabase.class)
public class SomeEntity extends BaseModel {

    @PrimaryKey(autoincrement = true)
    long id;

    @Column
    int order;

    @Column
    String name;

    @Column
    String filename;

    @Column
    String code;

    @Column
    String type;

    @Column
    int color;

    @Column
    long created;

    @Column
    long modified;

    public SomeEntity() {
        super();
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

  more getters and setters...
}`

**Comment by viethoang88** [comment]
+1 for this

My problem is similar. I am working on project where I sync database between iOS and Android app. 

So for example Entities that are coming from iOS and their primary IDs are not pretty. For example 
1, 2, 4, 6, 10, 15 (because some entities were removed) 

But when I insert into db on android it removes original id and set them as 
1, 2, 3, 4, 5, 6
this is causing issues because in referencing entity it lost the relation with original primary key.

**Comment by Essquilo** [comment]
I found out that `insert()` method is using String from `public final String getInsertStatementQuery()` of some table adapter. And that String from adapter lacks `id` if it's auto-incremented.

**Comment by agrosner** [comment]
This will be fixed in 3.0-beta4. What happened in since beta1 was actually the id was more of a ROWID, meaning it mirrored the maximum row number if you specified `autoincrement=true`. In (https://github.com/Raizlabs/DBFlow/blob/develop/dbflow-tests/src/test/java/com/raizlabs/android/dbflow/test/sql/FixPrimaryKeyMigration.java) there's a migration you can run to fix this on your table. The only way to fix it is to:
1. Create a temp table
2. Insert existing data into this table
3. Delete old table
4. Rename temp table to the original table

This is a one-time fix and if you used < 3.0.0-beta1 on certain devices with existing databases, they won't be affected. This will perform check to see if table was created properly.

**Comment by agrosner** [comment]
If you wish to keep beta1-beta3 behavior, just change `@PrimarKey(autoincrement=true)` to `@PrimaryKey(rowId=true)`

**Comment by agrosner** [comment]
in `develop`
