### ISSUE TITLE
Concatenate column values in where

### ISSUE THREAD

**Issue by sebastianmaz** [Raizlabs/DBFlow#690]
Is is possible to concatenate two text columns vales to use it in where clause ?

I would love to be able to do something like:

`select * from TABLE where (column1 || ' ' || column2) like '%something%' `

I use it often to compare provided value to street names with postcodes as one value.
I know I can use Property.concatenate but it only allows known string values.

**Comment by agrosner** [comment]
fixed in beta6

**Comment by Ivru** [comment]
I'm trying to do a request as mentioned by @sebastianmaz :
`SQLite.select()
    .from(Person.class)
    .where((Person_Table.asciiLastname.concatenate(" ").concatenate(Person_Table.asciiFirstname)).like("%" + mSearchTerms.toLowerCase() + "%"))`

Problem is, the concatenate seems not to work since it generate the following query:
`SELECT * 
FROM 'Person' 
WHERE 'asciiLastname' LIKE '%foobar%'`
instead of 
`SELECT * 
FROM 'Person' 
WHERE ('asciiLastname' || " " || 'asciiFirstname')  LIKE '%foobar%'`
as expected.

Am I doing it wrong ?
