### ISSUE TITLE
Support for SQLCipher?

### ISSUE THREAD

**Issue by tobrunvannuland** [Raizlabs/DBFlow#7]

**Comment by sregg** [comment]
I would to see SqlCipher integration as well.
@tobrunvannuland did you end up adding it yourself?

**Comment by faifai21** [comment]
@tobrunvannuland and @sregg, did you guys end up with an implementation of DBFlow with SQLCipher? Currently facing the same issue, would love to see SQLCipher integration

**Comment by JustinmClapperton** [comment]
I would also love to see support for SQLCipher.

**Comment by faifai21** [comment]
I went ahead and forked the library and added SQLCipher support (or rather, forced SQLCipher support). So far, I've noticed two things: 1) because of encryption, bulk inserts are noticeably longer (20% longer if I were to guess, maybe a bit more); and 2) because of bulk inserts taking longer, there has been an increase in the number of SQLiteDatabaseLockedException's. The second issue came about because I've got multiple sync adapters trying to put data into the database at around the same time when the app is first run. The generated ContentProviders do not take into account thread safety when writing to the database, so that is something I'll be looking at tomorrow. @tobrunvannuland, @sregg and @JustinmClapperton, feel free to ping me at faisal.alqadi@gmail.com if you're interested in helping out.

**Comment by agrosner** [comment]
@faifai21 yeah encrypted databases are always going to be slower than non-encrypted. In `2.0.0` I will allow custom subclasses of `FlowSQLiteOpenHelper`. For (2) I would place DB operations on the `DBTransactionQueue` to run them all in the same thread to prevent locking. I guess that is true-the generated `ContentProvider` do not "transact" the modifications or retrievals. That could be something worth looking into either by having a `FlowCursorLoader` or something else.

**Comment by spierce7** [comment]
+1

**Comment by Rainer-Lang** [comment]
+1
Any news?

**Comment by sevar83** [comment]
+1

**Comment by agilob** [comment]
+1

**Comment by FarhanAhmad** [comment]
+1

**Comment by TobiasReich** [comment]
+1 Any news regarding this?

**Comment by davidmaulick002** [comment]
There is support now for SqlCipher3 but will there be support for SqlCipher4 any time soon?
