### ISSUE TITLE
One version migration script path for different databases

### ISSUE THREAD

**Issue by bardzima** [Raizlabs/DBFlow#913]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Question

Description:
I'm using two different databases for different builds (db_name_release and db_name_debug). For now I'm duplicating version migration SQL scripts in two different asset locations: 'assets/migrations/db_name_release/' and 'assets/migrations/db_name_debug/'.

Question:
Is there any way to use the same path for version migration scripts for different databases?

**Comment by jesseiqmi** [comment]
Running into this as well.  Any thoughts dear DBFlow team on how to reduce/remove chances for broken builds due to having to manually maintain/copy migration files between release, debug, and even testing builds?  

I've seen that for test [RenamingDelegatingContext](https://developer.android.com/reference/android/test/RenamingDelegatingContext.html) works like a dream, but trying to find the same thing that we could implement for release/debug (and rolling up test into it at the same time).

A good analogy to this would be how Django and Rails migrations work - one set of descriptors for migrations in which the framework is build/environment aware.

Cheers and thanks!

**Comment by agrosner** [comment]
not sure what you mean two sets. if you include the migration in the main source assets and then they should share the same DB, then you wont have any issues. It looks like you have two different DBs?

**Comment by jesseiqmi** [comment]
@agrosner 

Hey sorry for getting back to you so late on this.

The case that I've given you is that I (as a Product Manager in part of my capacity) want to run the version of the app off the Play Store "release" so that I can work with clients, provide support, etc.  I also want to keep up with the devs (and dev myself) which is usually pegged with features that are not released yet "debug" (maybe worse case where we need to roll the DB back or uninstall due to self inflicted bugs etc). Here I want to maintain two separate DBs.

For our test strategy we using a renaming context on the database and are either testing "debug"/dev or "release"/master so it works as expected.

Maybe something has changed or maybe someone else has a way to work around what I'm needing where I have multiple versions ("debug"/"release") of the app installed on the same device.

At the moment we are duplicating the scripts but this can (has led) to possible issues.

Does that help?  Open to suggestions of course.

**Comment by jesseiqmi** [comment]
Hi @agrosner any thoughts or update on this?  Does my use case make sense?

**Comment by agrosner** [comment]
sorry for no response. you can specify them in different android resource directories. if you put them in `src/release/assets` and `src/debug/assets` they will get used.

**Comment by agrosner** [comment]
also just specifying a normal migration that resides the in the `src/release` or `src/debug` folder or on each other branches you can just execute the SQL yourself.
