### ISSUE TITLE
A custom date type converter does not get registered

### ISSUE THREAD

**Issue by schatekar** [Raizlabs/DBFlow#929]
A new android developer and first time user of DbFlow here. 

I am defining a customer date type converter as I want the dates to be stores in string format, something the default date converter does not offer. However, my customer date converter never gets registered. The `GeneratedDatabaseHolder` class only adds the default `DateConverter` class to the `typeConverters` hashmap. 

Am I doing anything wrong?

P.S. - I would have liked to label this issue as question but seems I cannot label issues on this repo.

**Comment by danvwells** [comment]
@agrosner  just discovered this is still a thing - the issue it causes is if you try to use an Enum property in a where clause with an in operator, such as ```where(...).in(...)```, then the enum's name is used instead of using the custom type converter.

A "solution" I'm using until I see a problem with it is to add another DatabaseHolder I'm calling ```CustomTypeConvertersHolder``` that adds my custom type converters to the holder's typeConverters map field, which get added to the globalDatabaseHolder's typeConverters map, and then the ```where(...).in(...)``` works.

Not sure if you want this one re-opened, or a new issue created... but at least it's here for posterity.  :)
