### ISSUE TITLE
Duplicated records are inserted if null value is used as Primary Key

### ISSUE THREAD

**Issue by sunny-chung** [Raizlabs/DBFlow#934]
DBFlow Version: 3.0.1
Issue Kind (Bug, Question, Feature): Bug

Description:

I use 3 columns as primary key and all of them are nullable. DBFlow always inserts if at least one of those primary keys is null.

I found the generated Adapter class only checks for value eq() in getPrimaryConditionClause(). However, eq() would fail for null values. Either isNull() should be added additionally for comparing null values, or implementation of eq() should be modified to return true if both values are null.

Sample model:
```java
@Table(database = Database.class)
public class A extends BaseModel {
    @PrimaryKey @Column @Nullable public String pk1;
    @PrimaryKey @Column public String pk2;
    @PrimaryKey @Column @Nullable public String pk3;

    @Column public String data;
}
```

Generated adapter class:
```java
  @Override
  public final ConditionGroup getPrimaryConditionClause(A model) {
    ConditionGroup clause = ConditionGroup.clause();
    clause.and(A_Table.pk1.eq(model.pk1));
    clause.and(A_Table.pk2.eq(model.pk2));
    clause.and(A_Table.pk3.eq(model.pk3));return clause;
  }
```

**Comment by sunny-chung** [comment]
In addition, a SQLiteException saying syntax error thrown if null was used as primary key value and calling BaseModel#update().

> net.sqlcipher.database.SQLiteException: near "`b`": syntax error: , while compiling: UPDATE  OR ABORT `A` SET `a`=?, `b`=?, `c`=?, `d`=? WHERE `a`='x' AND `b`='y' AND `d`=NULL`b`='y' AND `d`=NULL

It seems there is no workaround with DBFlow for allowing null values in primary key columns.

**Comment by trevjonez** [comment]
From [the docs](https://www.sqlite.org/lang_createtable.html)
`According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite. Unless the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is declared NOT NULL, SQLite allows NULL values in a PRIMARY KEY column. SQLite could be fixed to conform to the standard, but doing so might break legacy applications. Hence, it has been decided to merely document the fact that SQLite allowing NULLs in most PRIMARY KEY columns.`

Without the full stack trace it is not obvious if the failure is happening inside of sqlcipher or possibly lower inside of the platform sqlite engine. Regardless though it seems that this null primary key behavior should be avoided since it breaks the main SQL standard and could still be fixed in future version of SQLite.

As a work around you might consider defining a custom object type along with a custom type converter that you could use as the primary key in a single column, though it may make it less straightforward to query against the table and limit the effectiveness of indexing

**Comment by agrosner** [comment]
@trevjonez thanks for the helpful response. Will close this out.
