### ISSUE TITLE
Best way to import initially 200K entries from CSV

### ISSUE THREAD

**Issue by candeiasdan** [Raizlabs/DBFlow#940]
DBFlow Version: 3.1.1
Issue Kind (Bug, Question, Feature): Question

Description: 
I have a CSV file with nearly 200K (tops), but reading this file line by line and inserting item by item seems to take forever to populate the table.

What is the best approach to pre-populate a database with big set of data?

Thanks.

**Comment by trevjonez** [comment]
```java
FlowManager.getDatabase(AppDatabase.class).getTransactionManager().getSaveQueue().addAll(models);```

Start with using the save queue, that should help a lot. It is a separate thread that can be configured how often to save as well as manually triggered. Since you know the model count ahead of time you can increase the buffer size. I would say bump it up by a lot, this can have huge impact on the total time.

Take a look at https://github.com/Raizlabs/DBFlow/blob/master/dbflow/src/main/java/com/raizlabs/android/dbflow/runtime/DBBatchSaveQueue.java
to see how it works.

**Comment by carmas123** [comment]
My approach is this:
I request to server my data and server reply with a SQLite Database, now I attach the db to my SQLite DB and move all data into my destination database.

**Comment by ovidiucp** [comment]
I posted a similar issue in #954, together with an explanation of what I'm doing.

What you want to do instead is to generate a template database at build time. By placing this template database file in the `src/main/assets` directory of your Android project, you instruct DBFlow to make use of it the first time your application runs. DBFlow will copy the template database in the directory where the live database will be on the device, then start using it as it was just created. And bingo, you'll have a pre-populated database ready to use.

The nice thing about this approach is that the template database is generated offline, potentially automatically at build time. There is no runtime penalty of using this approach. The downside is that your app size will increase with the size of the template database, and since it's a read-only file you won't be able to delete it at runtime. But you already have this problem with the CSV file.
