### ISSUE TITLE
Ids getting lost

### ISSUE THREAD

**Issue by ricardomello** [Raizlabs/DBFlow#943]
DBFlow Version: 3.1.1
Issue Kind: Bug

Description: 

Hi, I've been using the lib for a few weeks without issues, but when I tried to add a way to sync the DB with a server I started having some trouble. 

I have 2 ids for the models, an internalId (primary key, autoIncrement = true) and a webId (so I can check when syncing and avoid having multiple rows of the same item). Whenever the app is opened I'll fetch the current data from the database to show the user and also fetch from the server the same data, if the data has anything new I'll save it and anything already in the database is ignored.

The problem is whenever I try to save the data from the server, for some reason all my rows lose their internalId - every row's internalId becomes 0, but my webId continues with the same correct value. 

I've tried different ways to do the same thing, onUniqueConflict = IGNORE/REPLACE on webId and saving only the items that are not on the database, all with the same result.

Am I missing something?

Thanks in advance.

**Comment by trevjonez** [comment]
What format is the external ID? and what is the justification for having a local ID as well as a remote ID, sounds like an ambiguity trap that will forever make communication difficult.

Can you post a code example showing exactly what your table looks like at least with the two ID columns defined?

**Comment by ricardomello** [comment]
```
public class Project extends BaseModel {
    @Column
    @PrimaryKey(autoincrement = true)
    int internalId;
    @Expose
    @Column
    @SerializedName("id")
    @Unique(onUniqueConflict = ConflictAction.IGNORE)
    String webId;
    @Expose
    @Column
    @SerializedName("name")
    String name;
    @Expose
    @Column
    @SerializedName("createdAt")
    Date createdAt;

    List<Report> reports;

    @OneToMany(methods = {OneToMany.Method.ALL}, variableName = "reports")
    public List<Report> getReports() {
        (...)
    }
}
```

The reason for an external ID is because the user can create a project while offline, when he goes online again the app will sync with the server and create the local project there, so when I receive the response from the server I only need to add the external ID to it.

Again this external ID is only used for checking if the item from the server is already in the database, the actual ID is the integer internalID. Also, since there are relations (One to Many with Report), simply replacing the internal item with the external one would mean the reports would be lost.

Thanks!

**Comment by trevjonez** [comment]
From [this page:](https://github.com/Raizlabs/DBFlow/blob/master/usage2/Models.md)
DBFlow supports multiple primary keys, right out of the box. Simply create a table with multiple @PrimaryKey:
```java
@Table(database = AppDatabase.class)
public class Dog extends BaseModel {

  @PrimaryKey
  String name;

  @PrimaryKey
  String breed;

}
```
If we want an auto-incrementing key, you specify @PrimaryKey(autoincrement = true), but only one of these kind can exist in a table and you cannot mix with regular primary keys.

Based on the last bit he says "and you cannot mix with regular primary keys" I don't think you will be able to do what you are asking without first figuring out why that restriction exists then attempting to modify the code base via pull request.

The system I work on is extremely similar to what you are trying to accomplish here. The solution that we came to was that on a post call to the server for a new object the id field (UUIDv4) is optional so we can actually assign the ID while in offline mode, while our web app can continue to allow the server to auto assign the new ID's.

As for the one to many relationship I would suggest that you analyze the current schema compared to the schema you would have if you used only the string ID. From there it should be fairly straightforward to create a migration so that the integrity of your relationships is not lost (assuming you have already shipped to customers with the existing schema).

**Comment by ricardomello** [comment]
You mean create the id locally and having this id sent to the server? That way only one id would be needed. We haven't shipped the app yet, so any changes can be made easily.

Thanks for the insight!
