### ISSUE TITLE
SQLite CONTAINS command equivalent and Collate NOACCENTS

### ISSUE THREAD

**Issue by markfili** [Raizlabs/DBFlow#959]
DBFlow Version: 3.1.1
Issue Kind : Question/Feature

Description: 
1. How to create a query with CONTAINS?
2. Is it possible to add Collate.NOACCENTS to Select method?

**Comment by trevjonez** [comment]
1. Look at using a "Method" object.
2. I am not sure of any easy way, however creative use of the decorator
pattern may yield the accent less query. Hopefully we can find a simpler
way.

On Aug 25, 2016 4:50 AM, "markfili" <notifications@github.com> wrote:

DBFlow Version: 3.1.1
Issue Kind : Question/Feature

Description:
1. How to create a query with CONTAINS?
2. How to strip accents from column values, i.e. manipulate data, when
performing SELECT?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Raizlabs/DBFlow/issues/959>, or mute the thread

**Comment by agrosner** [comment]
@markfili is this a valid SQLite collation? I dont seem to find any documentation on it.
